/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddChannel: typeof import('./src/components/childTool/addChannel.vue')['default']
    BDButton: typeof import('./src/components/BD-Button.vue')['default']
    ChartsSideBar: typeof import('./src/components/childTool/chartsSideBar.vue')['default']
    CheckboxTransfer: typeof import('./src/components/Checkbox-Transfer.vue')['default']
    ChildHeader: typeof import('./src/components/childTool/childHeader.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTextarea: typeof import('element-plus/es')['ElTextarea']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FileIcon: typeof import('./src/components/File-Icon.vue')['default']
    Footer: typeof import('./src/components/footer.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InputSearch: typeof import('./src/components/Input-Search.vue')['default']
    JoinChannel: typeof import('./src/components/childTool/joinChannel.vue')['default']
    Loading: typeof import('./src/components/Loading/Loading.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    Main: typeof import('./src/components/message/main.vue')['default']
    MarkDown: typeof import('./src/components/PaperEdit/MarkDown.vue')['default']
    MarkDownEditor: typeof import('./src/components/PaperEdit/MarkDownEditor.vue')['default']
    PageHeader: typeof import('./src/components/PaperEdit/PageHeader.vue')['default']
    Pagenate: typeof import('./src/components/pagenate.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    Progressbar: typeof import('./src/components/popup-progress/Progressbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/PaperEdit/SideBar.vue')['default']
    UserCard: typeof import('./src/components/childTool/UserCard.vue')['default']
    WordSideBar: typeof import('./src/components/childTool/wordSideBar.vue')['default']
  }
}
